### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by moepman** [freifunkMUC/wgkex#19]
This project should probably be renamed since wireguard-tools is the package name for the package providing `wg` e.g. in debian.

My favorite would probably be wireguard-key-exchange.

**Comment by awlx** [comment]
I think this is a really good idea. As we don't want to be confused with the actual wireguard-tools of @zx2c4.

@mweinelt what do you think of the new name?

**Comment by mweinelt** [comment]
Another idea that comes to mind is wireguard-broker. Because it literally brokers connections, the key exchange is only a part of that.

**Comment by zx2c4** [comment]
Can you use the wg- prefix instead? Makes it easier to distinguish upstream releases from project tools.

**Comment by awlx** [comment]
I am also fine with wg-key-exchange :).

**Comment by zx2c4** [comment]
> I am also fine with wg-key-exchange :).

Sounds good to me!

Will be cool to also see this spread to other Freifunks and then to other meshes. I'm happy you guys are pioneering this stuff!

**Comment by awlx** [comment]
Renamed the project! Thank you @zx2c4 for your support and kind words! :)

I think naming the whole project wg-key-exchange is fine then we can name the components wg-key-exchange-broker and wg-key-exchange-client.

**Comment by moepman** [comment]
Maybe closing was premature: README and package naming needs an update. PR coming soon.
