### ISSUE TITLE
Server and client component

### ISSUE THREAD

**Issue by awlx** [freifunkMUC/wgkex#4]
We should split that tool in a server and client component.
Maybe MQTT to exchange the pubkey and subscribe to a specific endpoint:
https://github.com/beerfactory/hbmqtt

**Comment by mweinelt** [comment]
Please focus on getting things up and running first. Reimplementing an MQTT broker, when mosquitto already exists seems wasteful.

**Comment by awlx** [comment]
Working on it in #29 and simple preview in #25
