### ISSUE TITLE
Fix pypi publish workflow

### ISSUE THREAD

**Issue by awlx** [freifunkMUC/wgkex#40]
At the moment the workflow is broken. We need a new way to publish wgkex to pypi.

https://github.com/freifunkMUC/wgkex/blob/main/.github/workflows/publish.yml

Maybe @rucarrol-goog you want to take a look if this is possible with bazel?

**Comment by rucarrol-goog** [comment]
I will look into using bazel to perform this actions, however I'll first need to finish adding `BUILD` files for the entire project. 

I'll put this on hold until then.
