### ISSUE TITLE
BUG: Iterate over ALL peers

### ISSUE THREAD

**Issue by lemoer** [freifunkMUC/wgkex#41]
I think you are affected by [this](https://github.com/freifunkh/wireguard-vxlan-glue/commit/7c876de05a30f4ff946065a34d5f9a63555d316f) as well. Look [here](https://github.com/freifunkMUC/wgkex/blob/f776463cb6206b0d08650acc1893a601ed01365c/wgkex/worker/netlink.py#L182).

**Comment by awlx** [comment]
We are not using this function at all at the moment :D. So probably we never stumbled across. But you are correct!

Are you willing to open a PR?
