### ISSUE TITLE
Use Netlink on the client to setup wireguard and vxlan

### ISSUE THREAD

**Issue by awlx** [freifunkMUC/wgkex#5]
There is a python library to setup tunnel devices via netlink:
https://github.com/svinota/pyroute2

**Comment by awlx** [comment]
https://docs.pyroute2.org/wireguard.html
https://docs.pyroute2.org/iproute.html?#pyroute2.iproute.linux.RTNL_API.neigh

**Comment by DasSkelett** [comment]
Maybe helpful: https://github.com/ArgosyLabs/wgnlpy
Got the link from a recent discussion on the WireGuard mailing list, also sounds somewhat relevant: [Python Wrapper for wireguard-tools](https://lists.zx2c4.com/pipermail/wireguard/2020-August/005781.html)

**Comment by awlx** [comment]
> Maybe helpful: https://github.com/ArgosyLabs/wgnlpy
> Got the link from a recent discussion on the WireGuard mailing list, also sounds somewhat relevant: [Python Wrapper for wireguard-tools](https://lists.zx2c4.com/pipermail/wireguard/2020-August/005781.html)

I think using another lib when pyroute2 already has wireguard implemented does not make sense.

**Comment by awlx** [comment]
@lqb @moepman @mweinelt @krombel @DasSkelett added a branch here:
https://github.com/freifunkMUC/wgkex/tree/netlink_support

It works flawless so far, just needs to be integrated :).

**Comment by awlx** [comment]
Closed it's implemented via #25
